import { FormFieldTypesInterface } from "./src/utils/Types/FormFieldTypes"


export const Categories = [
    {   
        key: 1,
        name: 'Допомога',
        path: 'dopomoga',
        image: '/assets/images/categories/dopomoga-1944-2x.jpg',
        background_color: 'white !important',
        children: [
            {   
                key: 101,
                name: 'Дитячий одяг',
                // path: `${this.path}/dityachiy_odyag`,
                max_photo: 8,
            },
            {   
                key: 102,
                name: 'Дитяче взуття',
                // path: `${this.path}/dityache_vzutya`,
                max_photo: 8,
            },
            {   
                key: 103,
                name: 'Дитячі коляски',
                // path: `${this.path}/dityachi_kolyaski`,
                max_photo: 8,
            },
            {   
                key: 104,
                name: 'Дитячі автокрісла',
                // path: `${this.path}/dityachi_avtokrisla`,
                max_photo: 8,
            },
            {   
                key: 105,
                name: 'Дитячі меблі',
                // path: `${this.path}/dityachi_mebli`,
                max_photo: 8,
            },
            {   
                key: 106,
                name: 'Іграшки',
                // path: `${this.path}/igrashki`,
                max_photo: 8,
            },
            {   
                key: 107,
                name: 'Дитячий транспорт',
                // path: `${this.path}/dityachiy_transport`,
                max_photo: 8,
            },
            {   
                key: 108,
                name: 'Годування',
                // path: `${this.path}/goduvanya`,
                max_photo: 8,
            },
            {   
                key: 109,
                name: 'Товари для школярів',
                // path: `${this.path}/tovari_dlya_shkolariv`,
                max_photo: 8,
            },
            {   
                key: 110,
                name: 'Інші дитячі товари',
                // path: `${this.path}/inshi_dityachiy_tovari`,
                max_photo: 8,
            },
            // 'Дитячий одяг',
            // 'Дитяче взуття', 
            // 'Дитячі коляски', 
            // 'Дитячі автокрісла ',
            // 'Дитячі меблі',
            // 'Іграшки',
            // 'Дитячий транспорт',
            // 'Годування ',
            // 'Товари для школярів',
            // 'Інші дитячі товари',
        ]
    },
    {   
        key: 2,
        name: 'Дитячий світ',
        path: 'dityachiy_svit',
        image: '/assets/images/categories/detskiy-mir-36-2x.png',
        background_color: '#ffce32 !important',
        children: [
            {   
                key: 201,
                name: 'Дитячий одяг',
                // path: `${this.path}/dityachiy_odyag`,
                max_photo: 10,
            },
            {   
                key: 202,
                name: 'Дитяче взуття',
                // path: `${this.path}/dityache_vzutya`,
                max_photo: 10,
            },
            {   
                key: 203,
                name: 'Дитячі коляски',
                // path: `${this.path}/dityachi_kolyaski`,
                max_photo: 10,
            },
            {   
                key: 204,
                name: 'Дитячі автокрісла',
                // path: `${this.path}/dityachi_avtokrisla`,
                max_photo: 10,
            },
            {   
                key: 205,
                name: 'Дитячі меблі',
                // path: `${this.path}/dityachi_mebli`,
                max_photo: 10,
            },
            {   
                key: 206,
                name: 'Іграшки',
                // path: `${this.path}/igrashki`,
                max_photo: 10,
            },
            {   
                key: 207,
                name: 'Дитячий транспорт',
                // path: `${this.path}/dityachiy_transport`,
                max_photo: 10,
            },
            {   
                key: 208,
                name: 'Годування',
                // path: `${this.path}/dityachie_goduvanya`,
                max_photo: 10,
            },
            {   
                key: 209,
                name: 'Товари для школярів',
                // path: `${this.path}/tovari_dlya_shkolariv`,
                max_photo: 10,
            },
            {   
                key: 210,
                name: 'Інші дитячі товари',
                // path: `${this.path}/inshi_dityachi_tovari`,
                max_photo: 10,
            },
            // 'Дитячий одяг',
            // 'Дитяче взуття', 
            // 'Дитячі коляски', 
            // 'Дитячі автокрісла ',
            // 'Дитячі меблі',
            // 'Іграшки',
            // 'Дитячий транспорт',
            // 'Годування ',
            // 'Товари для школярів',
            // 'Інші дитячі товари',
        ]
    },
    {
        key: 3,
        name: 'Нерухомість',
        path: 'neruhomist',
        image: '/assets/images/categories/nedvizhimost-1-2x.png',
        background_color: '#3a77ff !important',
        children: [
            {   
                key: 301,
                name: 'Квартири',
                // path: `${this.path}/kvartiri`,
                max_photo: 15,
            },
            {   
                key: 302,
                name: 'Кімнати',
                // path: `${this.path}/kimnati`,
                max_photo: 15,
            },
            {   
                key: 303,
                name: 'Будинки',
                // path: `${this.path}/budinki`,
                max_photo: 15,
            },
            {   
                key: 304,
                name: 'Земля',
                // path: `${this.path}/zemlya`,
                max_photo: 15,
            },
            {   
                key: 305,
                name: 'Комерційна нерухомість',
                // path: `${this.path}/komerciyna_neruhomist`,
                max_photo: 15,
            },
            {   
                key: 306,
                name: 'Гаражі, парковки',
                // path: `${this.path}/garazhi_parkovki`,
                max_photo: 15,
            },
            {   
                key: 307,
                name: 'Подобова оренда житла',
                // path: `${this.path}/podobova_orenda_ghitla`,
                max_photo: 15,
            },
            {   
                key: 308,
                name: 'Нерухомість за кордоном',
                // path: `${this.path}/neruhomist_za_kordonom`,
                max_photo: 15,
            },
            // 'Квартири',
            // 'Кімнати',
            // 'Будинки',
            // 'Земля',
            // 'Комерційна нерухомість',
            // 'Гаражі, парковки',
            // 'Подобова оренда житла',
            // 'Нерухомість за кордоном ',
        ]
    },
    {
        key: 4,
        name: 'Авто',
        path: 'avto',
        image: '/assets/images/categories/transport-1532-2x.png',
        background_color: '#23e5db !important',
        children: [
            {   
                key: 401,
                name: 'Легкові автомобілі',
                // path: `${this.path}/legkovi_avtomobili`,
                max_photo: 20,
            },
            {   
                key: 402,
                name: 'Вантажні автомобілі',
                // path: `${this.path}/vantagni_avtomobili`,
                max_photo: 20,
            },
            {   
                key: 403,
                name: 'Автобуси',
                // path: `${this.path}/avtobusi`,
                max_photo: 20,
            },
            {   
                key: 404,
                name: 'Мото',
                // path: `${this.path}/moto`,
                max_photo: 20,
            },
            {   
                key: 405,
                name: 'Спецтехніка',
                // path: `${this.path}/spectechnika`,
                max_photo: 20,
            },
            {   
                key: 406,
                name: 'Сільгосптехніка',
                // path: `${this.path}/silgosptechnika`,
                max_photo: 20,
            },
            {   
                key: 407,
                name: 'Водний транспорт',
                // path: `${this.path}/vodniy_transport`,
                max_photo: 20,
            },
            {   
                key: 408,
                name: 'Інший транспорт',
                // path: `${this.path}/inshiy_transport`,
                max_photo: 20,
            },
            // 'Легкові автомобілі',
            // 'Вантажні автомобілі',
            // 'Автобуси',
            // 'Мото',
            // 'Спецтехніка',
            // 'Сільгосптехніка',
            // 'Водний транспорт',
            // 'Інший транспорт',
        ]
    },
    {
        key: 5,
        name: 'Робота',
        path: 'robota',
        image: '/assets/images/categories/rabota-6-2x.png',
        background_color: '#fff6d9 !important',
        children: [
            {   
                key: 501,
                name: 'Продажі, закупки',
                // path: `${this.path}/prodagi_zakupki`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Логістика/Склад/Доставка',
                // path: `${this.path}/logistika_sklad_dostavka`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Будівництв',
                // path: `${this.path}/budivnictvo`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Адмін персонал/НР',
                // path: `${this.path}/admin_personal_HR`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Охорона/безпека',
                // path: `${this.path}/ohorona_bezpeka`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Клінінг/Домашній персонал',
                // path: `${this.path}/klining_domashniy_personal`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Освіта',
                // path: `${this.path}/osvita`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Медицина',
                // path: `${this.path}/medicina`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'IT, компьютери',
                // path: `${this.path}/IT_compyuteri`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Банки, фінанси',
                // path: `${this.path}/banki_financi`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Нерухомість',
                // path: `${this.path}/neruhomist`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Реклама/дизайн',
                // path: `${this.path}/reklama_design`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Виробництво',
                // path: `${this.path}/virobnictvo`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Робота за кордоном',
                // path: `${this.path}/robota_za_kordonom`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Інші сфери зайнятості',
                // path: `${this.path}/inshi_sferi_zainyatosti`,
                max_photo: 10,
            },
            // 'Продажі, закупки',
            // 'Логістика/Склад/Доставка',
            // 'Будівництв',
            // 'Адмін персонал/НР',
            // 'Охорона/безпека',
            // 'Клінінг/Домашній персонал',
            // 'Освіта',
            // 'Медицина',
            // 'IT, компьютери',
            // 'Банки, фінанси',
            // 'Нерухомість',
            // 'Реклама/дизайн',
            // 'Виробництво',
            // 'Робота за кордоном', 
            // 'Інші сфери зайнятості'
        ]
    },
    {
        key: 6,
        name: 'Дім і сад',
        path: 'dim_i_sad',
        // image: '/assets/images/categories/dom-i-sad-899-2x.png',
        background_color: '#c8f8f6 !important',
        children: [
            {   
                key: 601,
                name: 'Меблі',
                // path: `${this.path}/mebli`,
                max_photo: 15,
            },
            {   
                key: 602,
                name: 'Продукти харчування',
                // path: `${this.path}/produkti_harchuvanya`,
                max_photo: 15,
            },
            {   
                key: 603,
                name: 'Сад/город',
                // path: `${this.path}/sad_gorod`,
                max_photo: 15,
            },
            {   
                key: 604,
                name: 'Предмети інтерьеру',
                // path: `${this.path}/predmeti_interyeru`,
                max_photo: 15,
            },
            {   
                key: 605,
                name: 'Будівництво/ремонт',
                // path: `${this.path}/bedivnitstvo_remont`,
                max_photo: 15,
            },
            {   
                key: 606,
                name: 'Інструменти',
                // path: `${this.path}/instrumenti`,
                max_photo: 15,
            },
            {   
                key: 607,
                name: 'Кімнатні рослини',
                // path: `${this.path}/kimnatni_roslini`,
                max_photo: 15,
            },
            {   
                key: 608,
                name: 'Посуд/кухонне приладдя',
                // path: `${this.path}/posud_kuhone_priladya`,
                max_photo: 15,
            },
            {   
                key: 609,
                name: 'Садовий інвертар',
                // path: `${this.path}/sadoviy_interyer`,
                max_photo: 15,
            },
            {   
                key: 610,
                name: 'Побутова хімія',
                // path: `${this.path}/pobutova_himiya`,
                max_photo: 15,
            },
            {   
                key: 6011,
                name: 'Інші товари для дому',
                // path: `${this.path}/inshi_tovari_dlya_domu`,
                max_photo: 15,
            },
            // 'Меблі',
            // 'Продукти харчування',
            // 'Сад/город',
            // 'Предмети інтерьеру',
            // 'Будівництво/ремонт',
            // 'Інструменти',
            // 'Кімнатні рослини',
            // 'Посуд/кухонне приладдя',
            // 'Садовий інвертар',
            // 'Побутова хімія',
            // 'Інші товари для дому'
        ]
    },
    {
        key: 7,
        name: 'Електроніка',
        path: 'elektronika',
        image: '/assets/images/categories/elektronika-37-2x.png',
        background_color: '#ffd6c9 !important',
        children: [
            {   
                key: 701,
                name: 'Телефони та аксесуари',
                // path: `${this.path}/telefoni_ta_aksesuari`,
                max_photo: 15,
            },
            {   
                key: 702,
                name: 'Компьютери та комплектуючі',
                // path: `${this.path}/compyuteri_ta_komplektuyuci`,
                max_photo: 15,
            },
            {   
                key: 703,
                name: 'Фото/відео',
                // path: `${this.path}/foto_video`,
                max_photo: 15,
            },
            {   
                key: 704,
                name: 'Тв/відеотехніка',
                // path: `${this.path}/tv_videotechnika`,
                max_photo: 15,
            },
            {   
                key: 705,
                name: 'Аудіотехника',
                // path: `${this.path}/audiotehnika`,
                max_photo: 15,
            },
            {   
                key: 706,
                name: 'Ігрові приставки',
                // path: `${this.path}/igrovi_pristavki`,
                max_photo: 15,
            },
            {   
                key: 707,
                name: 'Планшети/ел. книги',
                // path: `${this.path}/plansheti_electroni_knigi`,
                max_photo: 15,
            },
            {   
                key: 708,
                name: 'Ноутбуки',
                // path: `${this.path}/noutbuki`,
                max_photo: 15,
            },
            {   
                key: 709,
                name: 'Техніка для дому',
                // path: `${this.path}/technika_dlya_domu`,
                max_photo: 15,
            },
            {   
                key: 710,
                name: 'Техніка для кухні',
                // path: `${this.path}/technika_dlya_kuhni`,
                max_photo: 15,
            },
            {   
                key: 711,
                name: 'Кліматичне обладнання',
                // path: `${this.path}/klimatichne_obladnenya`,
                max_photo: 15,
            },
            {   
                key: 712,
                name: 'Індивідуальний догляд',
                // path: `${this.path}/individualniy_doglad`,
                max_photo: 15,
            },
            {   
                key: 713,
                name: 'Інша електроніка',
                // path: `${this.path}/insha_electronika`,
                max_photo: 15,
            },
            // 'Телефони та аксесуари',
            // 'Компьютери та комплектуючі',
            // 'Фото/відео',
            // 'Тв/відеотехніка',
            // 'Аудіотехника',
            // 'Ігрові приставки',
            // 'Планшети/ел. книги',
            // 'Ноутбуки',
            // 'Техніка для дому',
            // 'Техніка для кухні',
            // 'Кліматичне обладнання',
            // 'Індивідуальний догляд',
            // 'Інша електроніка'
        ]
    },
    {
        key: 8,
        name: 'Бізнес та послуги',
        image: '/assets/images/categories/uslugi-7-2x.png',
        background_color: '#ffce32 !important',
        children: [
            {   
                key: 801,
                name: 'Будівництво/ремонт',
                // path: `${this.path}/budivnitstvo_remont`,
                max_photo: 15,
            },
            {   
                key: 802,
                name: 'Фінансові послуги',
                // path: `${this.path}/finansovi_poslugi`,
                max_photo: 15,
            },
            {   
                key: 803,
                name: 'Перевезення',
                // path: `${this.path}/perevezenya`,
                max_photo: 15,
            },
            {   
                key: 804,
                name: 'Реклама/поліграфія/маркетинг',
                // path: `${this.path}/reklama_poligraphiya_marketing`,
                max_photo: 15,
            },
            {   
                key: 805,
                name: 'Няні/доглядальниці',
                // path: `${this.path}/nani_dogladalnici`,
                max_photo: 15,
            },
            {   
                key: 806,
                name: 'Сировина/матеріали',
                // path: `${this.path}/sirovina_materiali`,
                max_photo: 15,
            },
            {   
                key: 807,
                name: 'Краса/здоровья',
                // path: `${this.path}/krasa_zdorovya`,
                max_photo: 15,
            },
            {   
                key: 808,
                name: 'Обладнання',
                // path: `${this.path}/obladnanya`,
                max_photo: 15,
            },
            {   
                key: 809,
                name: 'Освіта/спорт',
                // path: `${this.path}/osvita_sport`,
                max_photo: 15,
            },
            {   
                key: 810,
                name: 'Продажа бізнесу',
                // path: `${this.path}/prodagha_biznesu`,
                max_photo: 15,
            },
            {   
                key: 811,
                name: 'Юридичні послуги',
                // path: `${this.path}/yuredicni_poslugi`,
                max_photo: 15,
            },
            {   
                key: 812,
                name: 'Прокат товарів',
                // path: `${this.path}/prokat_tovariv`,
                max_photo: 15,
            },
            {   
                key: 813,
                name: 'Інші послуги',
                // path: `${this.path}/inshi_poslugi`,
                max_photo: 15,
            },
            // 'Будівництво/ремонт',
            // 'Фінансові послуги',
            // 'Перевезення',
            // 'Реклама/поліграфія/маркетинг',
            // 'Няні/доглядальниці',
            // 'Сировина/матеріали',
            // 'Краса/здоровья',
            // 'Обладнання',
            // 'Освіта/спорт',
            // 'Продажа бізнесу',
            // 'Юридичні послуги',
            // 'Прокат товарів',
            // 'Інші послуги'
        ]
    },
    {
        key: 9,
        name: 'Мода і стиль',
        path: 'moda_i_stil',
        image: '/assets/images/categories/moda-i-stil-891-2x.png',
        background_color: '#ceddff !important',
        children: [
            {   
                key: 801,
                name: 'Жіночій одяг',
                // path: `${this.path}/budivnitstvo_remont`,
                max_photo: 20,
            },
            {   
                key: 801,
                name: 'Жіноче взуття',
                // path: `${this.path}/budivnitstvo_remont`,
                max_photo: 20,
            },
            {   
                key: 801,
                name: 'Чоловічий одяг',
                // path: `${this.path}/budivnitstvo_remont`,
                max_photo: 20,
            },
            {   
                key: 801,
                name: 'Чоловіше взуття',
                // path: `${this.path}/budivnitstvo_remont`,
                max_photo: 20,
            },
            {   
                key: 801,
                name: 'Жіночя білизна',
                // path: `${this.path}/budivnitstvo_remont`,
                max_photo: 20,
            },
            {   
                key: 801,
                name: 'Чоловіча білизна',
                // path: `${this.path}/budivnitstvo_remont`,
                max_photo: 20,
            },
            {   
                key: 801,
                name: 'Головні убори',
                // path: `${this.path}/budivnitstvo_remont`,
                max_photo: 20,
            },
            {   
                key: 801,
                name: 'Аксесуари',
                // path: `${this.path}/budivnitstvo_remont`,
                max_photo: 20,
            },
            {   
                key: 801,
                name: 'Одяг для вагітних',
                // path: `${this.path}/budivnitstvo_remont`,
                max_photo: 20,
            },
            {   
                key: 801,
                name: 'Спецодяг',
                // path: `${this.path}/budivnitstvo_remont`,
                max_photo: 20,
            },
            {   
                key: 801,
                name: 'Мода різне',
                // path: `${this.path}/budivnitstvo_remont`,
                max_photo: 20,
            },
            // 'Жіночій одяг',
            // 'Жіноче взуття',
            // 'Чоловічий одяг',
            // 'Чоловіше взуття',
            // 'Жіночя білизна',
            // 'Чоловіча білизна',
            // 'Головні убори',
            // 'Аксесуари',
            // 'Одяг для вагітних',
            // 'Спецодяг',
            // 'Мода різне',
        ]
    },
    {
        key: 10,
        name: 'Хоббі і спорт',
        image: '/assets/images/categories/hobbi-otdyh-i-sport-903-2x.png',
        background_color: '#c8f8f6 !important',
        children: [
            'Антикваріат',
            'Музичні инструменти',
            'Спорт',
            'Книгр/журнали',
            'Квитки',
            'Гуртки',
            'Інше'
        ]
    },
    {
        key: 11,
        name: 'Віддам безкоштовно',
        image: '/assets/images/categories/otdam-darom-1151-2x.png',
        background_color: '#ffd6c9 !important',
    },
    {
        key: 12,
        name: 'Обмін',
        image: '/assets/images/categories/obmen-barter-1153-2x.png',
        background_color: '#fff6d9 !important',
    },
    
]



export const TechData = [
    {
        name: 'Технічний стан',
        fieldType: FormFieldTypesInterface.checkboxes,
        values: [
            'На ходу, технічно справна',
            'Не бита',
            'Не фарбована',
            'Гаражне зберігання',
            'Перший власник',
            'Сервісна книжка',
            'Потребує кузовного ремонту',
            'Потребує ремонту ходової',
            'Потребує ремонту двигуна',
            'Після ДТП',
            'Не на ходу',
        ],
    },
    {
        name: 'Мультимедіа',
        fieldType: FormFieldTypesInterface.checkboxes,
        options: [
            'CD',
            'AUX',
            'Bluetooth',
            'USB',
            'Акустика',
            'Магнітола',
            'Підсилювач',
            'Сабвуфер',
            'Система навігації GPS',
            'Apple CarPlay',
            'Android Auto',
        ],
    },
    {
        name: 'Модифікація',
        fieldType: FormFieldTypesInterface.input
    },
    {
        name: 'Рік випуску*',
        fieldType: FormFieldTypesInterface.input
    },
]

