

export const Categories = [
    {   
        key: 1,
        name: 'Допомога',
        path: 'dopomoga',
        image: '/assets/images/categories/dopomoga-1944-2x.jpg',
        background_color: 'white !important',
        children: [
            {   
                key: 101,
                name: 'Дитячий одяг',
                path: `${this.path}/dityachiy_odyag`,
                max_photo: 8,
            },
            {   
                key: 102,
                name: 'Дитяче взуття',
                path: `${this.path}/dityache_vzutya`,
                max_photo: 8,
            },
            {   
                key: 103,
                name: 'Дитячі коляски',
                path: `${this.path}/dityachi_kolyaski`,
                max_photo: 8,
            },
            {   
                key: 104,
                name: 'Дитячі автокрісла',
                path: `${this.path}/dityachi_avtokrisla`,
                max_photo: 8,
            },
            {   
                key: 105,
                name: 'Дитячі меблі',
                path: `${this.path}/dityachi_mebli`,
                max_photo: 8,
            },
            {   
                key: 106,
                name: 'Іграшки',
                path: `${this.path}/igrashki`,
                max_photo: 8,
            },
            {   
                key: 107,
                name: 'Дитячий транспорт',
                path: `${this.path}/dityachiy_transport`,
                max_photo: 8,
            },
            {   
                key: 108,
                name: 'Годування',
                path: `${this.path}/goduvanya`,
                max_photo: 8,
            },
            {   
                key: 109,
                name: 'Товари для школярів',
                path: `${this.path}/tovari_dlya_shkolariv`,
                max_photo: 8,
            },
            {   
                key: 110,
                name: 'Інші дитячі товари',
                path: `${this.path}/inshi_dityachiy_tovari`,
                max_photo: 8,
            },
            // 'Дитячий одяг',
            // 'Дитяче взуття', 
            // 'Дитячі коляски', 
            // 'Дитячі автокрісла ',
            // 'Дитячі меблі',
            // 'Іграшки',
            // 'Дитячий транспорт',
            // 'Годування ',
            // 'Товари для школярів',
            // 'Інші дитячі товари',
        ]
    },
    {   
        key: 2,
        name: 'Дитячий світ',
        path: 'dityachiy_svit',
        image: '/assets/images/categories/detskiy-mir-36-2x.png',
        background_color: '#ffce32 !important',
        children: [
            {   
                key: 201,
                name: 'Дитячий одяг',
                path: `${this.path}/dityachiy_odyag`,
                max_photo: 10,
            },
            {   
                key: 202,
                name: 'Дитяче взуття',
                path: `${this.path}/dityache_vzutya`,
                max_photo: 10,
            },
            {   
                key: 203,
                name: 'Дитячі коляски',
                path: `${this.path}/dityachi_kolyaski`,
                max_photo: 10,
            },
            {   
                key: 204,
                name: 'Дитячі автокрісла',
                path: `${this.path}/dityachi_avtokrisla`,
                max_photo: 10,
            },
            {   
                key: 205,
                name: 'Дитячі меблі',
                path: `${this.path}/dityachi_mebli`,
                max_photo: 10,
            },
            {   
                key: 206,
                name: 'Іграшки',
                path: `${this.path}/igrashki`,
                max_photo: 10,
            },
            {   
                key: 207,
                name: 'Дитячий транспорт',
                path: `${this.path}/dityachiy_transport`,
                max_photo: 10,
            },
            {   
                key: 208,
                name: 'Годування',
                path: `${this.path}/dityachie_goduvanya`,
                max_photo: 10,
            },
            {   
                key: 209,
                name: 'Товари для школярів',
                path: `${this.path}/tovari_dlya_shkolariv`,
                max_photo: 10,
            },
            {   
                key: 210,
                name: 'Інші дитячі товари',
                path: `${this.path}/inshi_dityachi_tovari`,
                max_photo: 10,
            },
            // 'Дитячий одяг',
            // 'Дитяче взуття', 
            // 'Дитячі коляски', 
            // 'Дитячі автокрісла ',
            // 'Дитячі меблі',
            // 'Іграшки',
            // 'Дитячий транспорт',
            // 'Годування ',
            // 'Товари для школярів',
            // 'Інші дитячі товари',
        ]
    },
    {
        key: 3,
        name: 'Нерухомість',
        path: 'neruhomist',
        image: '/assets/images/categories/nedvizhimost-1-2x.png',
        background_color: '#3a77ff !important',
        children: [
            {   
                key: 301,
                name: 'Квартири',
                path: `${this.path}/kvartiri`,
                max_photo: 15,
            },
            {   
                key: 302,
                name: 'Кімнати',
                path: `${this.path}/kimnati`,
                max_photo: 15,
            },
            {   
                key: 303,
                name: 'Будинки',
                path: `${this.path}/budinki`,
                max_photo: 15,
            },
            {   
                key: 304,
                name: 'Земля',
                path: `${this.path}/zemlya`,
                max_photo: 15,
            },
            {   
                key: 305,
                name: 'Комерційна нерухомість',
                path: `${this.path}/komerciyna_neruhomist`,
                max_photo: 15,
            },
            {   
                key: 306,
                name: 'Гаражі, парковки',
                path: `${this.path}/garazhi_parkovki`,
                max_photo: 15,
            },
            {   
                key: 307,
                name: 'Подобова оренда житла',
                path: `${this.path}/podobova_orenda_ghitla`,
                max_photo: 15,
            },
            {   
                key: 308,
                name: 'Нерухомість за кордоном',
                path: `${this.path}/neruhomist_za_kordonom`,
                max_photo: 15,
            },
            // 'Квартири',
            // 'Кімнати',
            // 'Будинки',
            // 'Земля',
            // 'Комерційна нерухомість',
            // 'Гаражі, парковки',
            // 'Подобова оренда житла',
            // 'Нерухомість за кордоном ',
        ]
    },
    {
        key: 4,
        name: 'Авто',
        path: 'avto',
        image: '/assets/images/categories/transport-1532-2x.png',
        background_color: '#23e5db !important',
        children: [
            {   
                key: 401,
                name: 'Легкові автомобілі',
                path: `${this.path}/legkovi_avtomobili`,
                max_photo: 20,
            },
            {   
                key: 402,
                name: 'Вантажні автомобілі',
                path: `${this.path}/vantagni_avtomobili`,
                max_photo: 20,
            },
            {   
                key: 403,
                name: 'Автобуси',
                path: `${this.path}/avtobusi`,
                max_photo: 20,
            },
            {   
                key: 404,
                name: 'Мото',
                path: `${this.path}/moto`,
                max_photo: 20,
            },
            {   
                key: 405,
                name: 'Спецтехніка',
                path: `${this.path}/spectechnika`,
                max_photo: 20,
            },
            {   
                key: 406,
                name: 'Сільгосптехніка',
                path: `${this.path}/silgosptechnika`,
                max_photo: 20,
            },
            {   
                key: 407,
                name: 'Водний транспорт',
                path: `${this.path}/vodniy_transport`,
                max_photo: 20,
            },
            {   
                key: 408,
                name: 'Інший транспорт',
                path: `${this.path}/inshiy_transport`,
                max_photo: 20,
            },
            // 'Легкові автомобілі',
            // 'Вантажні автомобілі',
            // 'Автобуси',
            // 'Мото',
            // 'Спецтехніка',
            // 'Сільгосптехніка',
            // 'Водний транспорт',
            // 'Інший транспорт',
        ]
    },
    {
        key: 5,
        name: 'Робота',
        path: 'robota',
        image: '/assets/images/categories/rabota-6-2x.png',
        background_color: '#fff6d9 !important',
        children: [
            {   
                key: 501,
                name: 'Продажі, закупки',
                path: `${this.path}/prodagi_zakupki`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Логістика/Склад/Доставка',
                path: `${this.path}/logistika_sklad_dostavka`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Будівництв',
                path: `${this.path}/budivnictvo`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Адмін персонал/НР',
                path: `${this.path}/admin_personal_HR`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Охорона/безпека',
                path: `${this.path}/ohorona_bezpeka`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Клінінг/Домашній персонал',
                path: `${this.path}/klining_domashniy_personal`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Освіта',
                path: `${this.path}/osvita`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Медицина',
                path: `${this.path}/medicina`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'IT, компьютери',
                path: `${this.path}/IT_compyuteri`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Банки, фінанси',
                path: `${this.path}/banki_financi`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Нерухомість',
                path: `${this.path}/neruhomist`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Реклама/дизайн',
                path: `${this.path}/reklama_design`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Виробництво',
                path: `${this.path}/virobnictvo`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Робота за кордоном',
                path: `${this.path}/robota_za_kordonom`,
                max_photo: 10,
            },
            {   
                key: 501,
                name: 'Інші сфери зайнятості',
                path: `${this.path}/inshi_sferi_zainyatosti`,
                max_photo: 10,
            },
            // 'Продажі, закупки',
            // 'Логістика/Склад/Доставка',
            // 'Будівництв',
            // 'Адмін персонал/НР',
            // 'Охорона/безпека',
            // 'Клінінг/Домашній персонал',
            // 'Освіта',
            // 'Медицина',
            // 'IT, компьютери',
            // 'Банки, фінанси',
            // 'Нерухомість',
            // 'Реклама/дизайн',
            // 'Виробництво',
            // 'Робота за кордоном', 
            // 'Інші сфери зайнятості'
        ]
    },
    {
        key: 6,
        name: 'Дім і сад',
        path: 'dim_i_sad',
        image: '/assets/images/categories/dom-i-sad-899-2x.png',
        background_color: '#c8f8f6 !important',
        children: [
            {   
                key: 601,
                name: 'Меблі',
                path: `${this.path}/inshi_sferi_zainyatosti`,
                max_photo: 15,
            },
            {   
                key: 602,
                name: 'Продукти харчування',
                path: `${this.path}/inshi_sferi_zainyatosti`,
                max_photo: 15,
            },
            {   
                key: 603,
                name: 'Сад/город',
                path: `${this.path}/inshi_sferi_zainyatosti`,
                max_photo: 15,
            },
            {   
                key: 604,
                name: 'Предмети інтерьеру',
                path: `${this.path}/inshi_sferi_zainyatosti`,
                max_photo: 15,
            },
            {   
                key: 605,
                name: 'Будівництво/ремонт',
                path: `${this.path}/inshi_sferi_zainyatosti`,
                max_photo: 15,
            },
            {   
                key: 606,
                name: 'Інструменти',
                path: `${this.path}/inshi_sferi_zainyatosti`,
                max_photo: 15,
            },
            {   
                key: 607,
                name: 'Кімнатні рослини',
                path: `${this.path}/inshi_sferi_zainyatosti`,
                max_photo: 15,
            },
            {   
                key: 608,
                name: 'Посуд/кухонне приладдя',
                path: `${this.path}/inshi_sferi_zainyatosti`,
                max_photo: 15,
            },
            {   
                key: 609,
                name: 'Садовий інвертар',
                path: `${this.path}/inshi_sferi_zainyatosti`,
                max_photo: 15,
            },
            {   
                key: 610,
                name: 'Побутова хімія',
                path: `${this.path}/inshi_sferi_zainyatosti`,
                max_photo: 15,
            },
            {   
                key: 6011,
                name: 'Інші товари для дому',
                path: `${this.path}/inshi_sferi_zainyatosti`,
                max_photo: 15,
            },
            // 'Меблі',
            // 'Продукти харчування',
            // 'Сад/город',
            // 'Предмети інтерьеру',
            // 'Будівництво/ремонт',
            // 'Інструменти',
            // 'Кімнатні рослини',
            // 'Посуд/кухонне приладдя',
            // 'Садовий інвертар',
            // 'Побутова хімія',
            // 'Інші товари для дому'
        ]
    },
    {
        key: 7,
        name: 'Електроніка',
        image: '/assets/images/categories/elektronika-37-2x.png',
        background_color: '#ffd6c9 !important',
        children: [
            'Телефони та аксесуари',
            'Компьютери та комплектуючі',
            'Фото/відео',
            'Тв/відеотехніка',
            'Аудіотехника',
            'Ігрові приставки',
            'Планшети/ел. книги',
            'Ноутбуки',
            'Техніка для дому',
            'техніка для кухні',
            'Кліматичне обладнання',
            'Індивідуальний догляд',
            'Інша електроніка'
        ]
    },
    {
        key: 8,
        name: 'Бізнес та послуги',
        image: '/assets/images/categories/uslugi-7-2x.png',
        background_color: '#ffce32 !important',
        children: [
            'Будівництво/ремонт',
            'Фінансові послуги',
            'Перевезення',
            'Реклама/поліграфія/маркетинг',
            'Няні/доглядальниці',
            'Сировина/матеріали',
            'Краса/здоровь',
            'Обладнання',
            'Освіта/спорт',
            'Продажа бізнесу',
            'Юридичні послуги',
            'Прокат товарів',
            'Інші послуги'
        ]
    },
    {
        key: 9,
        name: 'Моді і стиль',
        image: '/assets/images/categories/moda-i-stil-891-2x.png',
        background_color: '#ceddff !important',
        children: [
            'Жіночій одяг',
            'Жіноче взуття',
            'Чоловічий одяг',
            'Чоловіше взуття',
            'Жіночя білизна',
            'Чоловіча білизна',
            'Головні убори',
            'Аксесуари',
            'Одяг для вагітних',
            'Спецодяг',
            'Мода різне',
        ]
    },
    {
        key: 10,
        name: 'Хоббі і спорт',
        image: '/assets/images/categories/hobbi-otdyh-i-sport-903-2x.png',
        background_color: '#c8f8f6 !important',
        children: [
            'Антикваріат',
            'Музичні инструменти',
            'Спорт',
            'Книгр/журнали',
            'Квитки',
            'Гуртки',
            'Інше'
        ]
    },
    {
        key: 11,
        name: 'Віддам безкоштовно',
        image: '/assets/images/categories/otdam-darom-1151-2x.png',
        background_color: '#ffd6c9 !important',
    },
    {
        key: 12,
        name: 'Обмін',
        image: '/assets/images/categories/obmen-barter-1153-2x.png',
        background_color: '#fff6d9 !important',
    },
    
]